version: '2'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12
            MYSQL_DATABASE: maxdb
            MYSQL_USER: max
            MYSQL_PASSWORD: 12 
        volumes:
            - ./db:/var/lib/mysql

    php5:
        build: ./php5/
        links:
            - db
        ports:
            - 80:80
        depends_on:
            - db
        volumes:
            - ../www:/var/www/html
            - ./etc/apache2/sites-enabled/:/etc/apache2/sites-enabled/
#            - ./etc/apache2/:/etc/apache2/
        environment:
            - VIRTUAL_HOST=content.loc

    # php7:
    #     build: ./php7/
    #     links:
    #         - db
    #         - mongo
    #         - dbmaria
    #     ports:
    #         - 81:80
    #     depends_on:
    #         - db
    #     volumes:
    #         - ../www:/var/www/html

#     nginx:
#         build:
#             context: ./nginx
#         volumes:
#             - ./logs/nginx/:/var/log/nginx
# #            - ./nginx/sites/:/etc/nginx/sites-available
#         ports:
#             - "80:80"
#             - "443:443"
#         links:
#             - php5

#     nginx:
#         #image: nginx
#         build:
#             context: ./nginx
#         #volumes:
#         #    - ./etc/nginx/conf.d:/etc/nginx/conf.d
# #            - ./mysite.template:/etc/nginx/conf.d/mysite.template
#         ports:
#             - "80:80"
#         links:
#             - php5
#         depends_on:
#             - php5


    # nginx-proxy:
    #     image: jwilder/nginx-proxy
    #     container_name: nginx-proxy
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - /var/run/docker.sock:/tmp/docker.sock:ro

    # whoami:
    #     image: jwilder/whoami
    #     container_name: whoami
    #     environment:
    #         - VIRTUAL_HOST=whoami.local

    phpmyadmin:
      depends_on:
            - db
      image: phpmyadmin/phpmyadmin
      restart: always
      links:
        - db
      ports:
        - 8183:80
      environment:
        PMA_HOST: db
        MYSQL_USERNAME: max
        MYSQL_ROOT_PASSWORD: 12
        PMA_ARBITRARY: 1