version: '2'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12
            MYSQL_DATABASE: maxdb
            MYSQL_USER: max
            MYSQL_PASSWORD: 12 
        volumes:
            - dbvolume:/var/lib/mysql

    php5:
        build: ./php5/
        links:
            - db
        ports:
            - 80:80
        depends_on:
            - db
        volumes:
            - ../www:/var/www/html
            - ./etc/apache2/sites-enabled/:/etc/apache2/sites-enabled/

    # php7:
    #     build: ./php7/
    #     links:
    #         - db
    #         - mongo
    #         - dbmaria
    #     ports:
    #         - 81:80
    #     depends_on:
    #         - db
    #     volumes:
    #         - ../www:/var/www/html

    phpmyadmin:
      depends_on:
            - db
      image: phpmyadmin/phpmyadmin
      restart: always
      links:
        - db
      ports:
        - 8183:80
      environment:
        PMA_HOST: db
        MYSQL_USERNAME: max
        MYSQL_ROOT_PASSWORD: 12
        PMA_ARBITRARY: 1


volumes:
    dbvolume: