version: '2'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12
            MYSQL_DATABASE: maxdb
            MYSQL_USER: max
            MYSQL_PASSWORD: 12 
        volumes:
            - ./db:/var/lib/mysql

    dbmaria:
        image: mariadb
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: 12
            MYSQL_DATABASE: maxdb
            MYSQL_USER: max
            MYSQL_PASSWORD: 12 
        volumes:
            - ./dbmaria:/var/lib/mysql

    mongo:
        image: mongo
        volumes:
            - ./mongodb:/data/db
        ports:
            - 27017:27017


    mongoexpress:
        image: mongo-express
        links:
            - mongo
        ports:
            - 8081:8081

    php5:
        build: ./php5/
        links:
            - db
        ports:
            - 80:80
        depends_on:
            - db
        volumes:
            - ./www:/var/www/html

    php7:
        build: ./php7/
        links:
            - db
            - mongo
            - dbmaria
        ports:
            - 81:80
        depends_on:
            - db
        volumes:
            - ./www:/var/www/html

    phpmyadmin:
      depends_on:
            - db
      image: phpmyadmin/phpmyadmin
      restart: always
      links:
        - db
        - dbmaria
      ports:
        - 8183:80
      environment:
        PMA_HOST: db
        MYSQL_USERNAME: max
        MYSQL_ROOT_PASSWORD: 12
        PMA_ARBITRARY: 1